### ISSUE TITLE
code snippets generally don't contain valid XML

### ISSUE THREAD

**Issue by nigelmegitt** [mdn/imsc#6]
Many (most, I think, but definitely not all) of the code in the `<textarea id="code">` elements are not valid XML because they exclude a valid XML prolog such as `<?xml version="1.1"?>` - is there any reason this has been omitted? Would it be okay to add it?

I ask because a colleague mentioned this very specifically to me, that he found it unfortunate that the MDN IMSC page examples do not include this.

**Comment by tairt** [comment]
For XML documents we need to distinguish two forms of conformance:

1. Well formedness
2. Validity

An XML document is well formed if it respects the syntax scheme of the XML specification. An XML document is valid against syntax constraints made by a specific vocabulary (e.g. TTML), often enforced by an DTD or XML schema.

I assume that your assumption is, that the IMSC examples are not well formed because they do not contain the XML Prolog. 

The XML Prolog can be empty and is therefore optional.

See also:

https://www.w3.org/TR/xml/#dt-valid

Rule 22:

` prolog  ::=  XMLDecl? Misc* (doctypedecl Misc*)?`  

The samples also contain nothing that would enforce refering to version 1.1 of XML. They conform to version XML 1.0.

The XML Prolog was left empty on purpose to keep the samples simple and only adding the absolutely necesssary. Therefore I would prefer to not include the XML declaration.

This is also a common practice for shorter samples (see for example in TTML2 https://www.w3.org/TR/2018/REC-ttml2-20181108/#example).

**Comment by nigelmegitt** [comment]
Thank you - I was indeed checking against XML 1.1, which changes the conformance requirement to:

```
prolog  ::=  XMLDec Misc* (doctypedec Misc*)?
```

And IMSC 1.1 [specifies](https://www.w3.org/TR/ttml-imsc1.1/#document-encoding) concrete encoding as XML 1.0 not 1.1.
